<MyGridLayout>

    GridLayout:
        cols: 1
        size: root.width, root.height
        Image:
            source: 'NAlogo.png'
            size: self.texture_size
        GridLayout:
            cols:2
            rows:2
            Label:
                text: "s421"
            CheckBox:
        
            Label: 
                text: "s401"
            CheckBox:
            
                
        Button:
            text: "Submit"
            font_size: 32